Repository icgc-argo/platform-ui, pull requests merged in 2020-05, with the labels that each got.

#1411 🔖 uikit 1.4.0
  uikit/package.release.json
Labels: uikit-1.4.0

#1413 Master mergeback
  package.json
Labels: 1.17.0

#1416 🔖💄 uikit 1.5.0
  uikit/Icon/icons/collection/user.tsx
  uikit/package.release.json
Labels: uikit-1.5.0

#1417 Rc/1.18.0
  components/pages/file-repository/SimpleBarChart/index.tsx
  components/pages/file-repository/StatsCard/StatItem.tsx
  package.json
  uikit/Icon/icons/collection/file.tsx
  uikit/Icon/icons/collection/filesize.tsx
  uikit/Icon/icons/collection/programs.tsx
  uikit/Icon/icons/collection/user.tsx
  uikit/package.release.json
Labels: 1.18.0

#1418 Master mergeback
  package.json
Labels: 1.18.0

#1439 Rc/1.20.0
  components/pages/file-repository/FacetPanel/index.tsx
  components/pages/file-repository/index.tsx
  components/pages/submission-system/donor/ClinicalTimeline/common.tsx
  components/pages/submission-system/donor/ClinicalTimeline/header.tsx
  components/pages/submission-system/donor/ClinicalTimeline/index.tsx
  components/pages/submission-system/donor/ClinicalTimeline/samples.tsx
  components/pages/submission-system/donor/ClinicalTimeline/stories.tsx
  components/pages/submission-system/donor/ClinicalTimeline/table.tsx
  components/pages/submission-system/donor/ClinicalTimeline/timeline.tsx
  components/pages/submission-system/donor/ClinicalTimeline/types.tsx
  components/pages/submission-system/donor/ClinicalTimeline/util.ts
  package.json
  uikit/NumberRangeField/index.tsx
  uikit/OptionsList/ViewAmountController.tsx
  uikit/OptionsList/index.tsx
  uikit/PageLayout/index.tsx
  uikit/SubMenu/styledComponents.tsx
Labels: 1.20.0

#1441 Master mergeback
  package.json
Labels: 1.20.0

#1458 Master mergeback
  package.json
Labels: 1.23.0

#1463 Rc/1.24.0
  components/pages/submission-system/program-clinical-submission/PageContent.tsx
  components/pages/submission-system/program-dashboard/DonorDataSummary/DonorSummaryTable.tsx
  components/pages/submission-system/program-dashboard/DonorDataSummary/DownloadButtons.tsx
  components/pages/submission-system/program-dashboard/DonorDataSummary/index.tsx
  package-lock.json
  package.json
Labels: 1.24.0

#1464 Master mergeback
  package-lock.json
  package.json
Labels: 1.24.0

#1468 Rc/1.25.0
  .gitignore
  components/Footer.tsx
  components/NavBar.tsx
  components/pages/403.tsx
  components/pages/404.tsx
  components/pages/500.tsx
  components/pages/contact.tsx
  components/pages/error.tsx
  components/pages/login.tsx
  components/pages/submission-system/SchemaInvalidSubmissionNotification.tsx
  components/pages/submission-system/program-clinical-submission/Header.tsx
  components/pages/submission-system/program-clinical-submission/Instruction/index.tsx
  components/pages/submission-system/program-dashboard/CompletedClinicalData/index.tsx
  components/pages/submission-system/program-dashboard/DonorDataSummary/EmptyDonorSummaryTable.tsx
  components/pages/submission-system/program-dashboard/MolecularDataSummary/index.tsx
  components/pages/submission-system/program-dashboard/index.tsx
  components/pages/submission-system/program-management/index.tsx
  components/pages/submission-system/program-sample-registration/Instructions/index.tsx
  components/pages/submission-system/program-sample-registration/index.tsx
  components/pages/user/ApiTokenBox/index.tsx
  components/pages/user/ProgramAccessBox/DacoAccessStatusDisplay.tsx
  global/config.ts
  global/constants/docSitePaths.tsx
  global/constants/pages.tsx
  next.config.js
  package.json
  pages/maintenance.tsx
  tsconfig.json
  uikit/Footer/index.tsx
Labels: 1.25.0

#1469 Master mergeback
  package.json
Labels: 1.25.0

#1480 Master mergeback 1.26.0
  package.json
Labels: 1.26.0

#1483 Master mergeback
  package.json
Labels: 1.27.0

#1488 Rc/1.28.0
  components/NavBar.tsx
  components/pages/Homepage/ProgramServicesModal.tsx
  components/pages/Homepage/index.tsx
  components/pages/contact.tsx
  components/pages/contact/CREATE_JIRA_TICKET.gql
  components/pages/contact/common.tsx
  components/pages/contact/index.tsx
  global/config.ts
  package.json
  uikit/Icon/icons/collection/person_admin.tsx
  uikit/Icon/icons/collection/person_collaborator.tsx
  uikit/Icon/icons/collection/person_submitter.tsx
  uikit/Icon/icons/index.tsx
Labels: 1.28.0

#1489 Master mergeback
  package.json
Labels: 1.28.0

#1497 Master mergeback
  package.json
Labels: 1.29.0

#1503 Rc/1.30.0
  .env.schema
  components/Footer.tsx
  components/pages/403.tsx
  components/pages/404.tsx
  components/pages/500.tsx
  components/pages/MaintenancePage.tsx
  components/pages/submission-system/program-dashboard/CompletedClinicalData/index.tsx
  components/pages/submission-system/program-dashboard/MolecularDataSummary/index.tsx
  components/pages/team.tsx
  global/config.ts
  global/constants/pages.tsx
  next.config.js
  package.json
  pages/_app.tsx
  pages/maintenance.tsx
  pages/team.tsx
  static/group-33.svg
Labels: 1.30.0
