Repository icgc-argo/platform-ui, pull requests merged in 2020-06, with the labels that each got.

#1512 Rc/1.31.0
  components/NavBar.tsx
  components/pages/error.tsx
  components/pages/submission-system/layout.tsx
  components/pages/submission-system/program-clinical-submission/FilesNavigator/FileRecordTable.tsx
  components/pages/team.tsx
  next-env.d.ts
  package.json
Labels: 1.31.0

#1513 Master
  package.json
Labels: 1.31.0

#1519 Master mergeback
  package.json
Labels: 1.32.0

#1525 Rc/1.34.0
  components/Footer.tsx
  components/GdprMessage.tsx
  components/pages/privacy.tsx
  global/constants/argoPages.tsx
  global/constants/pages.tsx
  package.json
  pages/privacy.tsx
Labels: 1.34.0

#1526 Master mergeback
  package.json
Labels: 1.34.0

#1539 merge back to develop
  package.json
Labels: 1.36.0

#1546 Master mergeback
  package.json
Labels: 1.38.0

#1555 Rc/1.39.0
  components/pages/file-repository/FacetPanel/index.tsx
  components/pages/file-repository/FileTable/dummyData.tsx
  components/pages/file-repository/FileTable/index.tsx
  components/pages/file-repository/QueryBar/QueryBarContainer.tsx
  components/pages/file-repository/QueryBar/index.tsx
  components/pages/file-repository/QueryBar/stories.tsx
  components/pages/file-repository/hooks/useFiltersContext.tsx
  components/pages/file-repository/utils/index.ts
  components/pages/file-repository/utils/types.ts
  components/pages/submission-system/ErrorNotification.tsx
  package.json
  uikit/Facet/NumberRangeFacet/index.tsx
  uikit/Facet/NumberRangeFacet/stories.tsx
  uikit/Facet/index.tsx
  uikit/Facet/stories.tsx
  uikit/OptionsList/ViewAmountController.tsx
  uikit/OptionsList/index.tsx
  uikit/OptionsList/stories.tsx
  uikit/Table/TablePagination/index.tsx
Labels: 1.39.0

#1557 Master mergeback
  package.json
Labels: 1.39.0

#1594 Master mergeback 1.46.0
  package.json
Labels: 1.46.0

#1605 Rc/1.47.1
  package.json
Labels: 1.47.1

#1662 Master mergeback 1.57.0
  package.json
Labels: 1.57.0

#1668 Master mergeback 1.58.0
  package.json
Labels: 1.58.0

#1672 Master mergeback 1.59.0
  package.json
Labels: 1.59.0

#1674 Master mergeback 1.60.0
  package.json
Labels: 1.60.0
