Repository icgc-argo/platform-ui, pull requests merged in 2020-07, with the labels that each got.

#1684 Rc/1.63.0
  components/pages/user/ProgramAccessBox/DacoAccessStatusDisplay.tsx
  components/pages/user/ProgramAccessBox/index.tsx
  package.json
Labels: 1.63.0

#1685 Master mergeback 1.63.0
  package.json
Labels: 1.63.0

#1688 Master mergeback 1.64.0
  package.json
Labels: 1.64.0

#1707 Master mergeback 1.66.0
  package.json
Labels: 1.66.0

#1721 Maste rmergeback 1.69.0
  package.json
Labels: 1.69.0

#1724 Rc/1.70.0
  components/NavBar.tsx
  components/pages/Homepage/common.tsx
  components/pages/submission-system/common.tsx
  global/utils/common.tsx
  package-lock.json
  package.json
  uikit/AppBar/DropdownMenu.tsx
  uikit/AppBar/index.tsx
  uikit/AppBar/styledComponents.tsx
  uikit/Icon/icons/collection/hamburger.tsx
  uikit/Icon/icons/collection/hamburger_close.tsx
  uikit/Icon/icons/collection/info_transparent.tsx
  uikit/Icon/icons/collection/warning_transparent.tsx
  uikit/Icon/icons/index.tsx
  uikit/SystemAlert/index.tsx
  uikit/SystemAlert/stories.tsx
Labels: 1.70.0

#1729 Rc/1.71.0
  components/pages/submission-system/programs/ProgramsTable.tsx
  package.json
Labels: 1.71.0
